language: node_js
version: 1.0
node_js:
 - "14"
services:
 - docker
before_install:
 - docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli-v3:latest generate -i $SWAGGER_JSON -l typescript-angular -o /local -c /local/swagger_settings.json >/dev/null 
install:
 - npm install
before_script:
 - npm run build
before_deploy:
 - cd dist
 - sed -i "s/npm install PATH_TO_GENERATED_PACKAGE\/dist.tgz --save/npm install PATH_TO_GENERATED_PACKAGE\/dist.tgz --save\\n\`\`\`/" README.md
deploy:
  edge: true
  provider: npm
  api_key: "$NPM_API_KEY"
  email: "$NPM_EMAIL"
  skip_cleanup: true
  on:
    tags: true
    branch: master
 
notifications:
  email:
    on_success: never
    on_failure: never
