language: node_js
version: 1.0
node_js:
 - "14"
services:
 - docker
before_install:
 - docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i $SWAGGER_JSON -g typescript-angular --additional-properties=npmName=ng-configcat-publicapi,npmVersion=2.0.0 -o /local
install:
 - npm install
before_script:
 - npm run build
before_deploy:
 - cd dist
 - sed -i "s/npm install PATH_TO_GENERATED_PACKAGE\/dist.tgz --save/npm install PATH_TO_GENERATED_PACKAGE\/dist.tgz --save\\n\`\`\`/" README.md
deploy:
  edge: true
  provider: npm
  api_key: "$NPM_API_KEY"
  email: "$NPM_EMAIL"
  skip_cleanup: true
  on:
    tags: true
    branch: master
 
notifications:
  email:
    on_success: never
    on_failure: never
