/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represent the Feature Management permission.
 */
export type AccessType = 'readOnly' | 'full' | 'custom';

export const AccessType = {

    ReadOnly: 'readOnly' as AccessType,

    Full: 'full' as AccessType,

    Custom: 'custom' as AccessType
};

