/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the permission group level change request approval permission.
 */
export type ApprovalPermissionType = 'cannotApprove' | 'canApproveOthers' | 'canBypassApproves' | 'custom';

export const ApprovalPermissionType = {

    CannotApprove: 'cannotApprove' as ApprovalPermissionType,

    CanApproveOthers: 'canApproveOthers' as ApprovalPermissionType,

    CanBypassApproves: 'canBypassApproves' as ApprovalPermissionType,

    Custom: 'custom' as ApprovalPermissionType
};

