/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the permission group level change request approval permission.
 */
export const ApprovalPermissionType = {
    CannotApprove: 'cannotApprove',
    CanApproveOthers: 'canApproveOthers',
    CanBypassApproves: 'canBypassApproves',
    Custom: 'custom'
} as const;
export type ApprovalPermissionType = typeof ApprovalPermissionType[keyof typeof ApprovalPermissionType];

