/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueModel } from './valueModel';


/**
 * A percentage option for percentage-based user bucketing (for A/B testing), specifying a percentage range and the value to return.
 */
export interface AuditLogSettingValueV2EvaluationFormulaPercentageOptionModel { 
    /**
     * The percentage of users (0-100) who should receive the value.
     */
    percentage: number;
    value: ValueModel;
    /**
     * Optional name of the predefined variation for this percentage option.
     */
    valuePredefinedVariationName: string | null;
}

