/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditLogSettingValueV2EvaluationFormula } from './auditLogSettingValueV2EvaluationFormula';
import { SettingType } from './settingType';


/**
 * Model representing proposed changes to a Setting included in a Change Request.
 */
export interface ChangeRequestProposedChangeModel { 
    /**
     * Identifier of the Setting to change.
     */
    settingId: number;
    /**
     * Key identifier of the Setting.
     */
    settingKey: string;
    /**
     * Display name of the Setting.
     */
    settingName: string;
    /**
     * Optional hint or description for the Setting.
     */
    settingHint: string | null;
    settingType: SettingType;
    /**
     * Indicates whether the proposed changes to the Setting are in conflict with concurrently published changes.
     */
    hasConflict: boolean;
    originalEvaluationFormula: AuditLogSettingValueV2EvaluationFormula;
    proposedEvaluationFormula: AuditLogSettingValueV2EvaluationFormula;
}
export namespace ChangeRequestProposedChangeModel {
}


