/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChangeRequestSummaryModelPagedList } from './changeRequestSummaryModelPagedList';


/**
 * Wrapper model for a paginated list of Change Requests.
 */
export interface ChangeRequestsModel { 
    changeRequests: ChangeRequestSummaryModelPagedList;
}

