/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChangeRequestStatus } from './changeRequestStatus';


/**
 * Summary of a Change Request with essential information for list views.
 */
export interface ChangeRequestSummaryModel { 
    /**
     * Identifier of the Change Request.
     */
    changeRequestId: number;
    changeRequestStatus: ChangeRequestStatus;
    /**
     * Indicates whether the Change Request needs attention.
     */
    needsAttention: boolean;
    /**
     * Title of the Change Request.
     */
    title: string;
    /**
     * Optional notes describing the purpose of the Change Request.
     */
    reason: string | null;
    /**
     * Optional UTC date and time when the Change Request should be applied automatically.
     */
    applyAt: string | null;
    /**
     * The UTC date and time when the Change Request was created.
     */
    createdAt: string;
    /**
     * Email of the user who created the Change Request.
     */
    creatorUserEmail: string;
    /**
     * Full name of the user who created the Change Request.
     */
    creatorUserFullName: string;
    /**
     * Identifier of the creator user.
     */
    creatorUserId: string | null;
    /**
     * List of the keys of Settings affected by this Change Request.
     */
    affectedSettingKeys: Array<string>;
    /**
     * Number of comments on the Change Request.
     */
    commentCount: number;
    /**
     * Indicates whether the Change Request has been approved.
     */
    approved: boolean;
    /**
     * Number of conflicting settings in the Change Request.
     */
    conflictCount: number;
    /**
     * Indicates whether approval flow is bypassed.
     */
    bypassApproval: boolean;
    /**
     * Optional UTC date and time when the Change Request was applied.
     */
    appliedAt: string | null;
    /**
     * Identifier of the user who applied the Change Request.
     */
    appliedByUserId: string | null;
    /**
     * Email of the user who applied the Change Request.
     */
    appliedByUserEmail: string | null;
    /**
     * Full name of the user who applied the Change Request.
     */
    appliedByUserFullName: string | null;
    /**
     * Optional UTC date and time when the Change Request was closed.
     */
    closedAt: string | null;
    /**
     * Identifier of the user who closed the Change Request.
     */
    closedByUserId: string | null;
    /**
     * Email of the user who closed the Change Request.
     */
    closedByUserEmail: string | null;
    /**
     * Full name of the user who closed the Change Request.
     */
    closedByUserFullName: string | null;
}
export namespace ChangeRequestSummaryModel {
}


