/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ComparisonValueListModel { 
    /**
     * The actual comparison value.
     */
    value: string;
    /**
     * An optional hint for the comparison value.
     */
    hint: string | null;
}

