/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntegrationLinkModel } from './integrationLinkModel';
import { RolloutRuleModel } from './rolloutRuleModel';
import { SettingTagModel } from './settingTagModel';
import { RolloutPercentageItemModel } from './rolloutPercentageItemModel';
import { SettingDataModel } from './settingDataModel';


export interface ConfigSettingValueModel { 
    /**
     * The targeting rule collection.
     */
    rolloutRules?: Array<RolloutRuleModel> | null;
    /**
     * The percentage rule collection.
     */
    rolloutPercentageItems?: Array<RolloutPercentageItemModel> | null;
    /**
     * The value to serve. It must respect the setting type.
     */
    value?: any | null;
    setting?: SettingDataModel;
    /**
     * The last updated date and time when the Feature Flag or Setting.
     */
    updatedAt?: string | null;
    /**
     * The email of the user who last updated the Feature Flag or Setting.
     */
    lastUpdaterUserEmail?: string | null;
    /**
     * The name of the user who last updated the Feature Flag or Setting.
     */
    lastUpdaterUserFullName?: string | null;
    /**
     * The integration links attached to the Feature Flag or Setting.
     */
    integrationLinks?: Array<IntegrationLinkModel> | null;
    /**
     * The tags attached to the Feature Flag or Setting.
     */
    settingTags?: Array<SettingTagModel> | null;
}

