/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntegrationLinkModel } from './integrationLinkModel';
import { ValueModel } from './valueModel';
import { SettingDataV2Model } from './settingDataV2Model';
import { SettingTagModel } from './settingTagModel';
import { TargetingRuleModel } from './targetingRuleModel';


export interface ConfigSettingFormulaModel { 
    /**
     * The version identifier of the last change made to the Feature Flag or Setting in the Environment. It can be used to make sure concurrent updates are not overwriting each other. If the version identifier does not match the current version, the update will be rejected with a 409 Conflict response.
     */
    lastVersionId: string;
    defaultValue: ValueModel;
    /**
     * The targeting rules of the Feature Flag or Setting.
     */
    targetingRules: Array<TargetingRuleModel>;
    setting: SettingDataV2Model;
    /**
     * The last updated date and time when the Feature Flag or Setting.
     */
    updatedAt: string | null;
    /**
     * The user attribute used for percentage evaluation. If not set, it defaults to the `Identifier` user object attribute.
     */
    percentageEvaluationAttribute: string | null;
    /**
     * The email of the user who last updated the Feature Flag or Setting.
     */
    lastUpdaterUserEmail: string | null;
    /**
     * The name of the user who last updated the Feature Flag or Setting.
     */
    lastUpdaterUserFullName: string | null;
    /**
     * The integration links attached to the Feature Flag or Setting.
     */
    integrationLinks: Array<IntegrationLinkModel>;
    /**
     * The tags attached to the Feature Flag or Setting.
     */
    settingTags: Array<SettingTagModel>;
    /**
     * List of Feature Flag and Setting IDs where the actual Feature Flag or Setting is prerequisite.
     */
    settingIdsWherePrerequisite: Array<number>;
    /**
     * The number of change requests for the Feature Flag or Setting.
     */
    changeRequestCount: number;
}

