/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigModel } from './configModel';
import { ConfigSettingValueModel } from './configSettingValueModel';
import { EnvironmentModel } from './environmentModel';
import { FeatureFlagLimitations } from './featureFlagLimitations';


export interface ConfigSettingValuesModel { 
    config: ConfigModel;
    environment: EnvironmentModel;
    readOnly: boolean;
    settingValues: Array<ConfigSettingValueModel>;
    featureFlagLimitations: FeatureFlagLimitations;
}

