/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigModel } from './configModel';
import { ConfigSettingFormulaModel } from './configSettingFormulaModel';
import { EnvironmentModel } from './environmentModel';
import { FeatureFlagLimitations } from './featureFlagLimitations';


export interface ConfigSettingFormulasModel { 
    config?: ConfigModel;
    environment?: EnvironmentModel;
    readOnly?: boolean;
    /**
     * Evaluation descriptors of each updated Feature Flag and Setting.
     */
    settingFormulas?: Array<ConfigSettingFormulaModel> | null;
    featureFlagLimitations?: FeatureFlagLimitations;
}

