/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WebhookNotification } from './webhookNotification';


/**
 * The connection preferences for the proxy profile, including SDK poll interval and webhook proxy URL.
 */
export interface ConnectionPreferences { 
    /**
     * The SDK poll interval in seconds that determines how often SDKs should fetch config JSON updates.
     */
    sdkPollInterval: number;
    webhookNotification: WebhookNotification | null;
}

