/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnvironmentAccessType } from './environmentAccessType';
import { CreateOrUpdateEnvironmentAccessModel } from './createOrUpdateEnvironmentAccessModel';
import { AccessType } from './accessType';


export interface CreatePermissionGroupRequest { 
    /**
     * Name of the Permission Group.
     */
    name: string;
    /**
     * Group members can manage team members.
     */
    canManageMembers?: boolean;
    /**
     * Group members can create/update Configs.
     */
    canCreateOrUpdateConfig?: boolean;
    /**
     * Group members can delete Configs.
     */
    canDeleteConfig?: boolean;
    /**
     * Group members can create/update Environments.
     */
    canCreateOrUpdateEnvironment?: boolean;
    /**
     * Group members can delete Environments.
     */
    canDeleteEnvironment?: boolean;
    /**
     * Group members can create/update Feature Flags and Settings.
     */
    canCreateOrUpdateSetting?: boolean;
    /**
     * Group members can attach/detach Tags to Feature Flags and Settings.
     */
    canTagSetting?: boolean;
    /**
     * Group members can delete Feature Flags and Settings.
     */
    canDeleteSetting?: boolean;
    /**
     * Group members can create/update Tags.
     */
    canCreateOrUpdateTag?: boolean;
    /**
     * Group members can delete Tags.
     */
    canDeleteTag?: boolean;
    /**
     * Group members can create/update/delete Webhooks.
     */
    canManageWebhook?: boolean;
    /**
     * Group members can use the export/import feature.
     */
    canUseExportImport?: boolean;
    /**
     * Group members can update Product preferences.
     */
    canManageProductPreferences?: boolean;
    /**
     * Group members can add and configure integrations.
     */
    canManageIntegrations?: boolean;
    /**
     * Group members has access to SDK keys.
     */
    canViewSdkKey?: boolean;
    /**
     * Group members can rotate SDK keys.
     */
    canRotateSdkKey?: boolean;
    /**
     * Group members can create/update Segments.
     */
    canCreateOrUpdateSegments?: boolean;
    /**
     * Group members can delete Segments.
     */
    canDeleteSegments?: boolean;
    /**
     * Group members has access to audit logs.
     */
    canViewProductAuditLog?: boolean;
    /**
     * Group members has access to product statistics.
     */
    canViewProductStatistics?: boolean;
    accessType?: AccessType;
    newEnvironmentAccessType?: EnvironmentAccessType;
    /**
     * List of environment specific permissions.
     */
    environmentAccesses?: Array<CreateOrUpdateEnvironmentAccessModel> | null;
    /**
     * Group members can disable two-factor authentication for other members.
     */
    canDisable2FA?: boolean;
}
export namespace CreatePermissionGroupRequest {
}


