/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateEnvironmentModel { 
    /**
     * The name of the Environment.
     */
    name: string;
    /**
     * The color of the Environment. RGB or HTML color codes are allowed.
     */
    color?: string | null;
    /**
     * The description of the Environment.
     */
    description?: string | null;
    /**
     * The order of the Environment represented on the ConfigCat Dashboard. Determined from an ascending sequence of integers.
     */
    order?: number | null;
}

