/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateEvaluationFormulaWithLatestVersionModel } from './updateEvaluationFormulaWithLatestVersionModel';


export interface CreateChangeRequestProposedChangeModel { 
    proposedChange: UpdateEvaluationFormulaWithLatestVersionModel;
}

