/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateOrUpdateConnectionPreferences } from './createOrUpdateConnectionPreferences';
import { UpdateProxyProfileSelectionRule } from './updateProxyProfileSelectionRule';


export interface CreateOrUpdateProxyProfileRequest { 
    /**
     * The name of the proxy profile.
     */
    name: string;
    /**
     * The description of the proxy profile.
     */
    description?: string | null;
    connectionPreferences?: CreateOrUpdateConnectionPreferences | null;
    /**
     * A collection of selection rules that determine the SDK keys applicable for a proxy profile.
     */
    sdkKeySelectionRules?: Array<UpdateProxyProfileSelectionRule> | null;
}

