/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnvironmentAccessType } from './environmentAccessType';


export interface EnvironmentAccessModel { 
    /**
     * Identifier of the Environment.
     */
    environmentId: string;
    /**
     * Name of the Environment.
     */
    name: string;
    /**
     * Color of the Environment.
     */
    color: string | null;
    /**
     * Description of the Environment.
     */
    description: string | null;
    /**
     * The order of the Environment represented on the ConfigCat Dashboard.
     */
    order: number;
    /**
     * Determines whether a mandatory reason must be given every time when the Feature Flags or Settings in the given Environment are saved.
     */
    reasonRequired: boolean;
    environmentAccessType: EnvironmentAccessType;
}
export namespace EnvironmentAccessModel {
}


