/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConfigModel } from './configModel';
import { EnvironmentModel } from './environmentModel';
import { ProductModel } from './productModel';
import { SettingDataModel } from './settingDataModel';


export interface IntegrationLinkDetail { 
    product?: ProductModel;
    config?: ConfigModel;
    environment?: EnvironmentModel;
    setting?: SettingDataModel;
    readOnly?: boolean;
    status?: string | null;
}

