/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperationType } from './operationType';


export interface JsonPatchOperation { 
    op: OperationType;
    /**
     * The source path.
     */
    path: string;
    /**
     * The target path.
     */
    from?: string | null;
    /**
     * The discrete value.
     */
    value?: any | null;
}
export namespace JsonPatchOperation {
}


