/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Determines the Feature Flag key generation mode.
 */
export const KeyGenerationMode = {
    CamelCase: 'camelCase',
    LowerCase: 'lowerCase',
    UpperCase: 'upperCase',
    PascalCase: 'pascalCase',
    KebabCase: 'kebabCase'
} as const;
export type KeyGenerationMode = typeof KeyGenerationMode[keyof typeof KeyGenerationMode];

