/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Filters Change Requests by whether they need attention.
 */
export const NeedsAttentionFilter = {
    NotNeedsAttention: 'notNeedsAttention',
    NeedsAttention: 'needsAttention'
} as const;
export type NeedsAttentionFilter = typeof NeedsAttentionFilter[keyof typeof NeedsAttentionFilter];

