/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OperationType = 'unknown' | 'add' | 'remove' | 'replace' | 'move' | 'copy' | 'test';

export const OperationType = {
    Unknown: 'unknown' as OperationType,
    Add: 'add' as OperationType,
    Remove: 'remove' as OperationType,
    Replace: 'replace' as OperationType,
    Move: 'move' as OperationType,
    Copy: 'copy' as OperationType,
    Test: 'test' as OperationType
};

