/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationPermissionModel } from './organizationPermissionModel';


/**
 * Describes an Organization Member.
 */
export interface OrganizationMemberModel { 
    /**
     * Identifier of the Organization Admin.
     */
    userId: string;
    /**
     * Name of the Organization Admin.
     */
    fullName: string;
    /**
     * Email of the OrganizationAdmin.
     */
    email: string;
    /**
     * Determines whether 2FA is enabled for the Organization Admin.
     */
    twoFactorEnabled: boolean;
    /**
     * The permissions of the Member.
     */
    permissions: Array<OrganizationPermissionModel>;
}

