/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PagingResponseInfo { 
    currentPage: number;
    totalPages: number;
    pageSize: number;
    totalCount: number;
    readonly hasPrevious: boolean;
    readonly hasNext: boolean;
}

