/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueModel } from './valueModel';


export interface PercentageOptionModel { 
    /**
     * A number between 0 and 100 that represents a randomly allocated fraction of the users.
     */
    percentage: number;
    value: ValueModel;
}

