/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PredefinedVariationValueModel } from './predefinedVariationValueModel';


/**
 * A Feature Flag or Predefined Variation.
 */
export interface PredefinedVariationModel { 
    value: PredefinedVariationValueModel;
    /**
     * The name of the Feature Flag or Predefined Variation, shown on the Dashboard UI. If not set, the Value will be shown.
     */
    name: string | null;
    /**
     * The name of the Feature Flag or Predefined Variation, shown on the Dashboard UI. If not set, the Value will be shown.
     */
    hint: string | null;
    /**
     * The Feature Flag or Predefined Variation\'s identifier.
     */
    predefinedVariationId: string;
}

