/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PredefinedVariationEnvironmentModel } from './predefinedVariationEnvironmentModel';
import { PredefinedVariationWithUsagesModel } from './predefinedVariationWithUsagesModel';
import { SettingType } from './settingType';


export interface PredefinedVariationsWithUsagesModel { 
    /**
     * Key of the Feature Flag or Setting.
     */
    settingKey: string;
    settingType: SettingType;
    /**
     * The Feature Flag or Setting\'s Variations.
     */
    predefinedVariations: Array<PredefinedVariationWithUsagesModel>;
    /**
     * The Environment descriptors for the Variations\' usages.
     */
    environments: Array<PredefinedVariationEnvironmentModel>;
    /**
     * The maximum number of predefined variations allowed for the Feature Flag or Setting.
     */
    maxPredefinedVariations: number;
}
export namespace PredefinedVariationsWithUsagesModel {
}


