/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProxyProfileSdkKeyItem { 
    /**
     * The primary SDK Key of the Config / Environment pair selected for the Proxy Profile.
     */
    primarySdkKey: string;
    /**
     * The secondary SDK Key of the Config / Environment pair selected for the Proxy Profile.
     */
    secondarySdkKey: string | null;
    /**
     * The SDK ID identifying the Config / Environment pair selected for the Proxy Profile.
     */
    sdkId: string;
    /**
     * The identifier of the Config associated with the SDK key.
     */
    configId: string;
    /**
     * The identifier of the Environment associated with the SDK key.
     */
    environmentId: string;
}

