/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SdkKeysModel { 
    /**
     * The primary SDK key.
     */
    primary?: string | null;
    /**
     * The secondary SDK key.
     */
    secondary?: string | null;
}

