/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The segment comparison operator used during the evaluation process.
 */
export const SegmentComparator = {
    IsIn: 'isIn',
    IsNotIn: 'isNotIn'
} as const;
export type SegmentComparator = typeof SegmentComparator[keyof typeof SegmentComparator];

