/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StaleFlagEnvironmentModel } from './staleFlagEnvironmentModel';
import { StaleFlagConfigModel } from './staleFlagConfigModel';


export interface StaleFlagProductModel { 
    /**
     * Identifier of the Product.
     */
    productId: string;
    /**
     * Name of the Product.
     */
    name: string;
    /**
     * Configs that contain stale feature flags.
     */
    configs: Array<StaleFlagConfigModel>;
    /**
     * Environment list.
     */
    environments: Array<StaleFlagEnvironmentModel>;
}

