/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const StaleFlagReminderScope = {
    All: 'all',
    WatchedByMe: 'watchedByMe'
} as const;
export type StaleFlagReminderScope = typeof StaleFlagReminderScope[keyof typeof StaleFlagReminderScope];

