/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StaleFlagReminderScope = 'all' | 'watchedByMe';

export const StaleFlagReminderScope = {

    All: 'all' as StaleFlagReminderScope,

    WatchedByMe: 'watchedByMe' as StaleFlagReminderScope
};

