/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdatePredefinedVariationModel } from './updatePredefinedVariationModel';


export interface UpdatePredefinedVariationsRequest { 
    /**
     * A collection of Feature Flag or Predefined Variations.
     */
    predefinedVariations: Array<UpdatePredefinedVariationModel>;
}

