/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateApproveRequiredEnvironmentModel } from './updateApproveRequiredEnvironmentModel';
import { KeyGenerationMode } from './keyGenerationMode';
import { UpdateReasonRequiredEnvironmentModel } from './updateReasonRequiredEnvironmentModel';


export interface UpdatePreferencesRequest { 
    /**
     * Indicates that a mandatory note is required for saving and publishing.
     */
    reasonRequired?: boolean | null;
    keyGenerationMode?: KeyGenerationMode | null;
    /**
     * Indicates whether a variation ID\'s must be shown on the ConfigCat Dashboard.
     */
    showVariationId?: boolean | null;
    /**
     * Indicates whether Feature flags and Settings must have a hint.
     */
    mandatorySettingHint?: boolean | null;
    /**
     * List of Environments where mandatory note must be set before saving and publishing.
     */
    reasonRequiredEnvironments?: Array<UpdateReasonRequiredEnvironmentModel> | null;
    /**
     * Indicates that a mandatory approval is required before changes are applied.
     */
    approveRequired?: boolean | null;
    /**
     * List of Environments where mandatory approval must be given before changes are applied.
     */
    approveRequiredEnvironments?: Array<UpdateApproveRequiredEnvironmentModel> | null;
}
export namespace UpdatePreferencesRequest {
}


