/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnvironmentAccessType } from './environmentAccessType';
import { CreateOrUpdateEnvironmentAccessModel } from './createOrUpdateEnvironmentAccessModel';
import { AccessType } from './accessType';


export interface UpdatePermissionGroupRequest { 
    /**
     * Name of the Permission Group.
     */
    name?: string | null;
    /**
     * Group members can manage team members.
     */
    canManageMembers?: boolean | null;
    /**
     * Group members can create/update Configs.
     */
    canCreateOrUpdateConfig?: boolean | null;
    /**
     * Group members can delete Configs.
     */
    canDeleteConfig?: boolean | null;
    /**
     * Group members can create/update Environments.
     */
    canCreateOrUpdateEnvironment?: boolean | null;
    /**
     * Group members can delete Environments.
     */
    canDeleteEnvironment?: boolean | null;
    /**
     * Group members can create/update Feature Flags and Settings.
     */
    canCreateOrUpdateSetting?: boolean | null;
    /**
     * Group members can attach/detach Tags to Feature Flags and Settings.
     */
    canTagSetting?: boolean | null;
    /**
     * Group members can delete Feature Flags and Settings.
     */
    canDeleteSetting?: boolean | null;
    /**
     * Group members can create/update Tags.
     */
    canCreateOrUpdateTag?: boolean | null;
    /**
     * Group members can delete Tags.
     */
    canDeleteTag?: boolean | null;
    /**
     * Group members can create/update/delete Webhooks.
     */
    canManageWebhook?: boolean | null;
    /**
     * Group members can use the export/import feature.
     */
    canUseExportImport?: boolean | null;
    /**
     * Group members can update Product preferences.
     */
    canManageProductPreferences?: boolean | null;
    /**
     * Group members can add and configure integrations.
     */
    canManageIntegrations?: boolean | null;
    /**
     * Group members has access to SDK keys.
     */
    canViewSdkKey?: boolean | null;
    /**
     * Group members can rotate SDK keys.
     */
    canRotateSdkKey?: boolean | null;
    /**
     * Group members can create/update Segments.
     */
    canCreateOrUpdateSegments?: boolean | null;
    /**
     * Group members can delete Segments.
     */
    canDeleteSegments?: boolean | null;
    /**
     * Group members has access to audit logs.
     */
    canViewProductAuditLog?: boolean | null;
    /**
     * Group members has access to product statistics.
     */
    canViewProductStatistics?: boolean | null;
    /**
     * Group members can disable two-factor authentication for other members.
     */
    canDisable2FA?: boolean | null;
    accessType?: AccessType;
    newEnvironmentAccessType?: EnvironmentAccessType;
    /**
     * List of environment specific permissions.
     */
    environmentAccesses?: Array<CreateOrUpdateEnvironmentAccessModel> | null;
}
export namespace UpdatePermissionGroupRequest {
}


