/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateRolloutRuleModel } from './updateRolloutRuleModel';
import { SettingValueType } from './settingValueType';
import { UpdateRolloutPercentageItemModel } from './updateRolloutPercentageItemModel';


export interface UpdateSettingValueModel { 
    /**
     * The targeting rule collection.
     */
    rolloutRules?: Array<UpdateRolloutRuleModel>;
    /**
     * The percentage rule collection.
     */
    rolloutPercentageItems?: Array<UpdateRolloutPercentageItemModel>;
    /**
     * The value to serve. It must respect the setting type. In some generated clients for strictly typed languages you may use double/float properties to handle integer values.
     */
    value: SettingValueType;
}

