/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The webhook notification settings, including the proxy URL and signing keys.
 */
export interface WebhookNotification { 
    /**
     * The webhook proxy URL for receiving config JSON change notifications.
     */
    webhookProxyUrl: string;
    /**
     * The primary signing key used for verifying the authenticity of webhook requests.
     */
    signingKey1: string;
    /**
     * The secondary signing key used for verifying the authenticity of webhook requests.
     */
    signingKey2: string | null;
}

