/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WebHookHttpMethod } from './webHookHttpMethod';
import { WebhookHeaderModel } from './webhookHeaderModel';


export interface WebHookRequestModel { 
    /**
     * The URL of the Webhook.
     */
    url: string;
    /**
     * The HTTP body content.
     */
    content?: string | null;
    httpMethod?: WebHookHttpMethod | null;
    /**
     * List of HTTP headers.
     */
    webHookHeaders?: Array<WebhookHeaderModel> | null;
}
export namespace WebHookRequestModel {
}


