/**
 * ConfigCat Public Management API
 *
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const WebHookHttpMethod = {
    Get: 'get',
    Post: 'post'
} as const;
export type WebHookHttpMethod = typeof WebHookHttpMethod[keyof typeof WebHookHttpMethod];

