name: Public API Angular CI

on:
  push:
    branches: [ master ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
  
jobs:
  buildandpublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Install dependencies
        run: npm i
          
      - name: Build
        run: npm run build

      - name: 🚀Publish
        if: startsWith(github.ref, 'refs/tags')
        run: npm publish --access public
        working-directory: ./dist/ng-configcat-publicapi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_KEY }}
